### ISSUE TITLE
How should Response setters work?

### ISSUE THREAD

**Issue by matthewwithanm** [matthewwithanm/monorouter#14]
How should `notFound`, `doctype`, and `contentType` work? They could just be simple properties, e.g.

``` javascript
Router.route('...', function(req) {
  this.notFound = true;
  this.doctype = 'html5';
});
```

On the other hand, making them functions might be nice for chaining:

``` javascript
Router.route('...', function(req) {
  this.notFound().doctype('html5');
});
```

But then how would you get the values?

**Comment by lettertwo** [comment]
Chaining is cool, but i like the properties.  Maybe we could also pass them as opts to the `end` methods? I guess the `render` methods could support it too, as a third arg after the optional view props...

**Comment by matthewwithanm** [comment]
Yeah, we can worry about shortcuts like that later though, I think.

**Comment by matthewwithanm** [comment]
One nice thing about methods though is that if you type it wrong, you'll get an error…

**Comment by lettertwo** [comment]
true, but if they are methods, do they end up being `getNotFound` and `setNotFound`?
