### ISSUE TITLE
Return `this.ended` from `endInitial()`?

### ISSUE THREAD

**Issue by matthewwithanm** [matthewwithanm/monorouter#16]
This would make using a single non-generator handler easy even when rendering a different initial view:

``` javascript
router.route('...', function(req) {
  // snip

  if (this.endInitial()) return;

  this.render(SomethingElse);
});
```

If we do this, should we do the same for `renderInitial` and remove the chainability?

**Comment by lettertwo** [comment]
It makes sense to me for the `end` and `render` methods not to be chainable. This seems like a good use of a return value, too.
