### ISSUE TITLE
Rename Router.renderInto

### ISSUE THREAD

**Issue by matthewwithanm** [matthewwithanm/monorouter#18]
All off the other render methods (including `engine.renderInto`) are short-lived; this one takes over a DOM element for its lifetime.

@lettertwo Can you think of anything good?

**Comment by lettertwo** [comment]
Maybe something like attach or mount?

**Comment by matthewwithanm** [comment]
Yeah, I like those. Another option is to have the constructor accept an element…

**Comment by lettertwo** [comment]
Or maybe a Backbone-inspired term like start.

**Comment by matthewwithanm** [comment]
Yeah, I thought of `start` and `init` but they're so generic and (I think) underemphasize the relationship of the operation to the DOM.

**Comment by matthewwithanm** [comment]
I went with `attach()` but I'm open to changing it if we think of something better.
