### ISSUE TITLE
Add request-scoped view vars?

### ISSUE THREAD

**Issue by matthewwithanm** [matthewwithanm/monorouter#22]
Currently, there are three ways to set values for the object passed to the view function:
1. Pass a `defaultVars` opt when creating the router
   - This is meant for internal use since user code doesn't normally create router instances directly.
   - They are persisted for the life of the router instance.
2. Call `setState` on the response object
   - These are persisted across requests for the entire life of a router instance.
3. Pass them as a second arg to one of the response's `render*` methods.
   - These are bound to the view and only last as long as that view is rendered.

In thinking there might be a need for another that functions like the third but is done independently of setting a view. Basically, "set props for any subsequent views rendered by this route." The rational is that this would be useful for middleware (like the domCache). Currently, this could be accomplished by overriding `setView`:

``` javascript
function myMiddleware(req) {
  var oldSetView = this.view;
  this.view = function(vars) {
    return oldView.call(this, extend(vars, {
      scopedViewVar: whatever
    }));
  };
}
```

Though this seems like a lot of boilerplate.

So should we add API for this? If so, what?

**Comment by lettertwo** [comment]
We'll, it's late and I'm basically asleep, but those aren't excuses if these ideas are bad:
1. Maybe `setState` could behave this way, and some other function should set state that persists
2. Maybe a response object could differentiate these 'localized' functions from the 'global' ones
