### ISSUE TITLE
Change handler signature; add `initial()`

### ISSUE THREAD

**Issue by matthewwithanm** [matthewwithanm/monorouter#3]
I don't think the `done` callback is going to work because it assumes that the final state is also the initial one (i.e. the one you render on the server). This may be true often, but isn't necessarily true always.

Given that a single callback won't cut it, we should probably bite the bullet and make the routes async by default and mark it as done using something like express's `end()` (to indicate that the request is done processing and we're at the final state), as well as a method to indicate that we're at the initial state (`initial()`?).

_Sidenote: we could come up with an alternate way to do synchronous handlers separately. For example, if the handler returns a function…_

Given this signature change, I think we should also consider getting rid of Response and RoutingContext entirely and moving their functionality onto Request. (The "response" terminology was always dubious for browser code anyway.) The end result would be a Request object that looked like the current RoutingContext. I think that XHR and koa's context are good precedents for this single-object-that-represents-the-request-and-response approach.

So it would look something like this:
### Simple handler

``` javascript
Router.route('users/:username', function(req) {
  req
    .setViewProps(getUser(req.params.username))
    .setView(UserDetail)
    .end();
});
```
### Async handler

``` javascript
Router.route('users/:username', function(req) {
  xhr('...', function(err, res) {
    req
      .setViewProps(res.user)
      .setView(UserDetail)
      .end();
  });
});
```
### Async handler w/different initial view

``` javascript
Router.route('users/:username',
  function(req) {
    req
      .setView(Loading)
      .initial();
  },
  function(req) {
    xhr('...', function(err, res) {
      req
        .setViewProps(res.user)
        .setView(UserDetail)
        .end();
    });
  }
);
```

Note that in the first two cases (where `initial()` isn't called), it's implied by the invocation of `end()`.
## Things to consider:
- [ ] Do we like the name `end()`?
- [ ] Do we like the name `initial()`?
  - At first I thought `serve()`, but that's weird for the browser.
  - As an adjective, it's not really symmetrical with `end()`
- [ ] Can the initial handler be async too?
  - It's probably useful, but…
  - If so, you can't just use `React.renderComponent` to render the router (since it wouldn't yet be in a renderable state.
    - `Router.renderInto()`?
    - This is a problem [with the current API as well](https://github.com/matthewwithanm/react-routing/blob/8c374b1310a41d5ed33c8555009ce833dcd9d6d8/lib/createRouterClass.js#L81-L82).
- [ ] Should we raise an error if you call `initial` and `end` in the same handler?
  - This means the server is doing work it never uses.

**Comment by matthewwithanm** [comment]
@lettertwo I think this is pretty much settled? Gonna close.

**Comment by lettertwo** [comment]
:thumbsup:
