### ISSUE TITLE
React rails integration

### ISSUE THREAD

**Issue by gauravtiwari** [matthewwithanm/monorouter#37]
Hey there,

Will monorouter work well with Rails using react-rails gem? It will be helpful if you can write an example. 

Thanks,
Gaurav

**Comment by matthewwithanm** [comment]
Hi @gauravtiwari. Honestly, I don't know! I don't use Rails so I'm not really familiar with what that gem does.

**Comment by gauravtiwari** [comment]
Thanks @matthewwithanm for replying. Basically, it's a simple module (think of it like bower component or NPM module) for rails. It packages React for rails with some built-in function. Sorry, let me put my question this way. Will mono router work with any server side framework? Django or Rails with their built in server side routing? I have some isomorphic small components built in react and lately I was thinking to build nested views for a page using react. Will monorouter work? Thank you :)

**Comment by matthewwithanm** [comment]
You might be able to rig up something like [connect-monorouter](https://github.com/matthewwithanm/connect-monorouter) but it would be a little strange. You'd not only have to call into the JS from Ruby but also have it call back post dispatch.
