### ISSUE TITLE
Route exception

### ISSUE THREAD

**Issue by stanonyime** [matthewwithanm/monorouter#42]
Is there a way to exempt a route from monorouter hijack. I want my /logout route to be handled server-side

**Comment by matthewwithanm** [comment]
Yeah, you can pass a "blacklist" option to `captureClicks`. It should be an array of strings or regular expressions to test the path against.

**Comment by stanonyime** [comment]
Thanks

**Comment by matthewwithanm** [comment]
:thumbsup:

**Comment by stanonyime** [comment]
Sorry. I'm getting "Uncaught TypeError: undefined is not a function" pointing to this line in the linkHijacker.prototype.start function:

``` javascript
this.element.addEventListener('click', this.handleClick);
```

**Comment by matthewwithanm** [comment]
How are you initializing the router?

**Comment by stanonyime** [comment]
``` javascript
var monorouter        =         require('monorouter');
var reactRouting      =         require('monorouter-react');
monorouter()
  .setup(reactRouting())
  .route('/', function(req) {
    this.render(HomePage);
  })
  .route('/update', function(req) {
    this.render(UpdatePage);
  })
   .route('/groups', function(req) {
    this.render(GroupPage);
  })
  .route('/:username', function(req) {
    this.render(ProfilePage,{username:req.params.username});
  }) 
  .attach(document.getElementById('app'))
  .captureClicks(['/a/logout']);
```

**Comment by matthewwithanm** [comment]
Can you log out `document.getElementById('app')` right before this code?

**Comment by stanonyime** [comment]
What do you mean by "log out"? Comment off?

**Comment by matthewwithanm** [comment]
Sorry, I just meant to log it to the console. So

``` javascript
console.log(document.getElementById('app'));
```

**Comment by matthewwithanm** [comment]
Oh, sorry. I see the issue. The signature for `captureClicks` is `(el, opts)`. So you should be doing something like this:

``` javascript
.captureClicks(window, {blacklist: ['/a/logout']})
```

**Comment by stanonyime** [comment]
Ok. Solved

**Comment by matthewwithanm** [comment]
:thumbsup: :thumbsup:
