### ISSUE TITLE
Trigger route on user-generated event

### ISSUE THREAD

**Issue by stanonyime** [matthewwithanm/monorouter#43]
How do I trigger a navigation to any of the defined routes clientside?

**Comment by matthewwithanm** [comment]
You can use the history object's `navigate` method, like the LinkHijacker [does](https://github.com/matthewwithanm/monorouter/blob/11bb1cd10e421bdd91982e5f2e6712e218c0b847/lib/LinkHijacker.js#L83).

**Comment by stanonyime** [comment]
ok

**Comment by stanonyime** [comment]
I was not able to get it to work. How do I invoke router.history.navigate from my own function? Is it like:
router = require('monorouter') ...?

**Comment by matthewwithanm** [comment]
No, you'll need a reference to the actual router instance—the thing returned by `monorouter()`.
