### ISSUE TITLE
Add koa support?

### ISSUE THREAD

**Issue by DylanPiercey** [matthewwithanm/monorouter#44]
Is it a consideration to add support for the koa framework? And if so is anyone considering adding async/generator support to this library?

**Comment by matthewwithanm** [comment]
Hey @DylanPiercey! monorouter itself doesn't really have to support koa. You just need to write a little bit of glue to connect them, like [connect-monorouter](https://github.com/matthewwithanm/connect-monorouter).

As for generator support, I don't have any plans right now.

Hope that helps!
