### ISSUE TITLE
Client Side Navigation Without Links

### ISSUE THREAD

**Issue by codematix** [matthewwithanm/monorouter#45]
Is there a way by which I can perform navigation to another view on the client-side without using links? For example:

``` jsx
module.exports = React.createClass({
  handleClick: function () {
    router.navigateTo('/payment', {source: 'checkout');
  },

  render: function () {
    return (<button type="button" onClick={this.handleClick}>Proceed To Payment</button>);
  }
});
```

**Comment by matthewwithanm** [comment]
Hi @codematix! Yeah, you can use the `navigate` method of the history object, just like [the link hijacker does](https://github.com/matthewwithanm/monorouter/blob/4173f267ca65f4d222865903e441b4d6b00f669d/lib/LinkHijacker.js#L82-L83).

**Comment by codematix** [comment]
Would it be wise to hold on to the reference of the `router` object instance as global variable?

**Comment by matthewwithanm** [comment]
Yeah, you'll need to keep a reference somewhere. How things talk to it is up to you: you can make it global, pass it to the things that need it using some form of DI, dispatch events that get observed and acted on (like the LinkHijacker), etc.

**Comment by codematix** [comment]
Alright. Closing issue. Thanks a lot!

**Comment by matthewwithanm** [comment]
np (:
