### ISSUE TITLE
using monorouter with babel

### ISSUE THREAD

**Issue by svnm** [matthewwithanm/monorouter#46]
I can't seem to get monorouter working with babel. 

I am using the isomorphic example. Following the babel documentation on working with webpack: https://babeljs.io/docs/setup/#webpack

I `npm install --save-dev babel-loader` then I change `jsx-loader` to `babel-loader`in the 2 webpack config.js files.

Now npm install, and npm start. But it gives an error: a very strange one: 

`var originalGlobalValue = exports.EventEmitter;  Cannot read property 'EventEmitter' of undefined`

Can you help me out, I was hoping to set up some monorouter examples using some different flux libraries.

Thanks

**Comment by svnm** [comment]
Even if I use the simple browser example I get the issue. `TypeError: Cannot read property 'EventEmitter' of undefined` as soon as I change the loader to `babel-loader` in the webpack.config.

Is it an issue with the use of event emitter https://github.com/Wolfy87/EventEmitter?

**Comment by matthewwithanm** [comment]
I'm not sure what would cause this error off the top of my head, but generally you would [exclude your `node_modules` directory from transforms](https://github.com/babel/babel-loader#usage):

``` js
  loaders: [
    {
      test: /\.jsx?$/,
      exclude: /(node_modules|bower_components)/,
      loader: 'babel?optional[]=runtime&stage=0'
    }
  ]
```

Is there a reason you need to include it?

**Comment by svnm** [comment]
I am still having problems with that updated loader.

I would think getting this to play nicely with Babel would be quite important as it is becoming the most common way to develop React/Flux sites/apps with Flummox and Alt both encouraging the use of es6 with Babel.

I will keep trying to get an example up with Babel/Monorouter/Webpack but if you have any time to set one up yourself it would be great, as I am keen to use this in my future projects.

**Comment by matthewwithanm** [comment]
Can you share your webpack config?

**Comment by svnm** [comment]
I am working directly off the monorouter examples, either the isomorphic one or browser one.
I run `npm install` 
then
`npm install --save-dev babel-loader`
then just changing the one line in the loader from `jsx` to `babel-loader`

**Comment by matthewwithanm** [comment]
Sorry, but I can't reproduce that. Everything works fine for me with the browser example, provided I use the latest versions of React, monorouter, and monorouter-react and remove the pragmas.

**Comment by svnm** [comment]
Is it possible you could copy the browser version, add in the babel loader as mentioned and add this to the examples as a babel example. I can clone it and see if I have an issue.

I am running on mac osx Mavericks with node v0.12.0 if it is of any help.

Thanks for your help. If I get this working I will be setting up as many flux examples as I can with Monorouter

**Comment by matthewwithanm** [comment]
Check out the [for-Stevenlseki](https://github.com/matthewwithanm/monorouter/tree/for-StevenIseki) branch (:

Tested in Chrome 43.0.2357.81 and FF 37.0.2

**Comment by svnm** [comment]
Wow, thanks so much for that. It works perfectly now. I could have sworn mine was exactly the same, I have mainly used Browserify in the past rather than Webpack, so I will use that as my excuse.

Thanks for that branch, I will be using it to create a set of monorouter flux examples and will get back to you when I am done. :)

**Comment by matthewwithanm** [comment]
Awesome (:

The examples should really all be switched over to Babel at some point. Just been too busy lately. Glad we got this sorted out though!

**Comment by svnm** [comment]
Sorry to open this again Matthew, 

I can't seem to get the isomorphic ones to work with babel. 
The main example I am trying to use is the lazyloadviews.

I update the 2 webpack.configs

```
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel?optional[]=runtime&stage=0'
      }
```

Then update the package.json as follows.

```
  "dependencies": {
    "express": "^4.7.2",
    "monorouter": "^0.11.3",
    "monorouter-react": "^0.4.1",
    "react": "^0.13.3",
    "webpack": "^1.3.2-beta9",
    "wolfy87-eventemitter": "^4.2.11",
    "connect-monorouter": "^0.2.1"
  },
  "devDependencies": {
    "babel-core": "^5.4.7",
    "babel-loader": "^5.1.3"
  }
```

Only I get a strange error `You need to dispatch absolute URLs on the server` probably again something wrong with how I am using webpack.

If you had a chance to update the lazload example on the for-Stevenlseki branch it would be great, and I will use that for my flux examples. Also happy to rewrite a version of each of the examples in babel too.

**Comment by svnm** [comment]
Actually I think it is more of an issue with the dependancies not working together. These are the dependancies I am trying to use for the isomorphic example.

```

"dependencies": {
    "express": "^4.7.2",
    "react": "^0.13.3",
    "monorouter": "^0.11.3",
    "monorouter-react": "^0.4.1",
    "connect-monorouter": "^0.4.0",
    "wolfy87-eventemitter": "^4.2.11",
    "webpack": "^1.3.2-beta9"
  },
  "devDependencies": {
    "babel-core": "^5.4.7",
    "babel-loader": "^5.1.3"
  }  

```

I noticed that in the browser example wolfy87-eventemitter was added, also we have bumped up monorouter, monorouter-react and react. 

So for me I cannot get it working with these dependancies
