### ISSUE TITLE
Figure out what do with optional props passed to render

### ISSUE THREAD

**Issue by lettertwo** [matthewwithanm/monorouter#9]
Right now the view is passed router state as a prop (`routerState`) _unless_ you provide props to `render`, in which case, the view can't access router state at all.

Should we:
- add `routerState` to optional props
- don't pass `routerState` at all (instead you would close over `this.state` in your handler)
- make `routerState` the props object (merging with optional props, if they exist)
- keep it as is

**Comment by matthewwithanm** [comment]
As of cb3134625acf6e1c012c6fa188d450e080d067d7, I'm merging them with the state and passing that to the view (option 3). Going to close this but feel free to reopen if you have objections/other ideas.
